// constants.js
export const fieldNames = {
  email: "Email",
  sexo: "Sexo",
  estadoCivil: "Estado Civil",
  tipoSanguineo: "Tipo Sanguíneo",
  uf_naturalidade: "UF de Naturalidade",
  uf_orgao: "UF do Órgão",
  uf_endereco: "UF do Endereço",
  escolaridade: "Escolaridade",
  dataContratacao: "Data de Contratação",
  dataDeNascimento: "Data de Nascimento",
  dataExpedicao: "Data de Expedição",
  cargo: "Cargo",
  lotacao: "Lotação",
  matricula: "Matrícula",
  nomeCompleto: "Nome Completo",
  naturalidade: "Naturalidade",
  rg: "RG",
  orgao: "Órgão",
  cpf: "CPF",
  nomeDaMae: "Nome da Mãe",
  nomeDoPai: "Nome do Pai",
  cep: "CEP",
  cidade: "Cidade",
  logradouro: "Logradouro",
  complemento: "Complemento",
  telefone: "Telefone",
  celular: "Celular",
  postoDeTrabalho: "Posto de Trabalho",
  orgaoExpedidor: "Órgão Expedidor",
  religiao: "Religião",
};

export const tipoSanguineoList = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
];
export const sexoList = ["Masculino", "Feminino"];
export const ufList = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];
export const estadoCivilList = ["Solteiro", "Casado", "Separado", "Viúvo"];
export const escolaridadeList = [
  "Ensino Fundamental",
  "Ensino Médio",
  "Ensino Superior",
  "Pós-Graduação",
  "Mestrado",
  "Doutorado",
];
